name: semeval
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml  
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip:
      - transformers>=4.40.0
      - accelerate>=0.29.0
      - tokenizers
      - sentencepiece
      - datasets
      - safetensors
      - comet_ml
      - python-dotenv
      - peft
      - pytorch-metric-learning
      - bitsandbytes
      - protobuf
      - scikit-learn
      - kaggle