name: semeval
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - pyarrow
  - fastparquet
  - pytorch>=2.6.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4 
  - pip:
      - transformers>=4.48.0
      - accelerate>=1.0.0
      - tokenizers
      - sentencepiece
      - datasets
      - safetensors
      - comet_ml
      - python-dotenv
      - peft
      - rich
      - regex
      - bitsandbytes
      - protobuf
      - scipy