name: semeval
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch>=2.4
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - pip
  - pip:
      - transformers>=4.48.0
      - accelerate>=1.0.0
      - pytorch_metric_learning
      - tokenizers
      - sentencepiece
      - datasets
      - safetensors
      - comet_ml
      - python-dotenv
      - peft
      - rich
      - regex
      - protobuf
      - scipy
      - bitsandbytes
      - kaggle